- name: acatest1
  image: repo/acatest1:v1
  args: "foo bar"
  command: "foo bar"
  env: "foo1=bar1, foo2=bar2"
  volumeMounts:
  - storageName: "string"
    name: "string"
    storageType:
    - AzureFile: "string"
      EmptyDir: "string"
  resources:
  - cpu: 0.5
    ephemeralStorage: "1Gi"
    memory: "250Mb"
  probes:
  - type: Liveness
    httpGet:
      path: "/health"
      httpHeaders:
      - name: Custom-Header
        value: Awesome
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
  - type: Liveness
    httpGet:
      path: "/health"
      httpHeaders:
      - name: Custom-Header
        value: Awesome
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
- name: acatest2
  image: repo/acatest2:v1
  probes:
  - type: Liveness
    httpGet:
      path: "/health"
      httpHeaders:
      - name: Custom-Header
        value: Awesome
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3