on: [push, pull_request]
  
name: Samlpe GitHub Action to create new revision of Container App

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
        registry-url: 'https://npm.pkg.github.com'

    - run: npm install
    - run: tsc

    # local debugging only.
    # Remove or comment out this step when running on GitHub.
    # - run: |
    #     which az || curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    #     npm install && npm run build

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Create a new Container App revision'
      uses: ./
      with:
        resource-group: rg-sample
        name: ctapp-sample
        image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
        revision-name-suffix: ${{ github.sha }}