on: [push, pull_request]
  
name: Container Deployment Sample Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
        registry-url: 'https://npm.pkg.github.com'

    # local debugging only.
    # Remove or comment out this step when running on GitHub.
    - run: |
        which az || curl -sL https://aka.ms/InstallAzureCLIDeb | bash
        npm install && npm run build

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Container Apps'
      uses: ./
      with:
        resource-group: rg-hoge
        name: ctapp-hoge
        location: 'Japan East'
        managed-environment-name: 'ctenv-hoge'
        dapr-app-port: 3000
        dapr-app-protocol: 'http'
        dapr-enabled: true
        ingress-external: true
        ingress-target-port: 3000
        ingress-traffic-json: |
          [ 
            { 
              "label": "production", 
              "revisionName": "yuhattor-container3--qpxyrnn", 
              "weight": 100 
            } 
          ]
        scale-max-replicas: 5
        scale-min-replicas: 1
        containers-config-json: | 
          [
            {
              "name":"simple-hello-world-container",
              "image": "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
            }
          ]

